### ISSUE TITLE
ewasm should use keccak256/ripemd160/sha2-256 system contract, not our own implementation

### ISSUE THREAD

**Issue by seanyoung** [hyperledger-labs/solang#268]
This will make the deployed contract code much smaller.

**Comment by sxysun** [comment]
Hi,

I have been reading this interesting project for sometime, and I am just curious that will this issue include changing the burrow chain implementation? Since pre-compiled contracts are hard-coded in the chain and thus if on the compiler level we have keccak256 translated to `call_EEI 0x9 ...` or something like that, it would need the burrow project to update their code first right? Wondering if burrow already have such implementation or what is the timeline of this.... Thanks!

**Comment by seanyoung** [comment]
@sxysun yes, you are right. Burrow needs to be updated for this to work properly. I don't have timelines at the moment, but having said that, it's not a lot of work.

**Comment by sxysun** [comment]
@seanyoung I see, thanks! Our project [deepsea](https://github.com/certikfoundation/deepsea)'s development kind of depends on the eei function resolvers in life VM supported on Burrow, so I think maybe I will also look into it and probably send a PR if you guys do not plan on supporting that soon
