### ISSUE TITLE
VS Code Extension is broken: 'Failed to download: Cannot read property 'browser_download_url' of undefined'

### ISSUE THREAD

**Issue by gorgos** [hyperledger-labs/solang#574]
From me looking into it, there seem to be several issues:

1. Wrong name used for downloading. Platform name is coming from here:
https://github.com/hyperledger-labs/solang/blob/10edadffab522cca59910cf50dec233e8437464f/vscode/src/utils/getPlatform.ts#L10-L11

    But the [download json](https://api.github.com/repos/hyperledger-labs/solang/releases/latest) name is actually `llvm13.0-mac-intel.tar.xz`.

2. Empty objects in JavaScript are truthy. `if ({}) console.log('truthy'); // truthy` So this check https://github.com/hyperledger-labs/solang/blob/10edadffab522cca59910cf50dec233e8437464f/vscode/src/utils/getServer.ts#L72 didn't catch the error.

3. I actually have `solang` already in my PATH installed. In this case any extra download/installation should not be required.

**Comment by seanyoung** [comment]
Please can you try again. The extension thinks the llvm 13 libraries release was the latest release. I've updated that to be a pre-release so it won't be listed as the latest release.

This is a bit messy because when moving llvm versions, I need to store the llvm libraries somewhere. Maybe I should have done a new release of solang.

You said you have a local copy of solang. We really need an option in the extension which says "use local version in $PATH" or "use solang version at this particular path" <select path>.

**Comment by seanyoung** [comment]
@gorgos what do you think of https://github.com/hyperledger-labs/solang/pull/577 ?

**Comment by gorgos** [comment]
@seanyoung Thanks, download is working now. Also the new option to use already installed binary looks great.
