### ISSUE TITLE
custom error reverts unsupported by solang-parser

### ISSUE THREAD

**Issue by mattsse** [hyperledger-labs/solang#696]
Stumbled upon this when looking at this for example https://github.com/withtally/rollcall/blob/main/src/Executor.sol 

which solang-parser fails to parse at the parentheses 

https://github.com/withtally/rollcall/blob/6ffdcffc41ba163a83a93f1b03c97815b6e49fa4/src/Executor.sol#L28

I couldn't find where "revert" is implemented so would need some pointers where to modify lalrpop rules for this before I can try fixing this

**Comment by seanyoung** [comment]
Right, this syntax is not supported yet. The syntax `error UNDERLYING_CONTRACT_REVERTED();` is supported, but the syntax to revert with an error is not: `revert UNDERLYING_CONTRACT_REVERTED();`

To make this work:
- Introduce a new keyword `revert` in lexer.rs
- Introduce a new statement `Revert(Loc, Expression)` in the parse tree (just like `Emit()`)
- Where `"emit" <ty:FunctionCall>` is parsed in the lalrpop file, add a `"revert" <ty:FunctionCall>`
- Add `revert` to `SolIdentifier` in the lalrpop file, so that `revert` can be used as a variable name
